### ISSUE TITLE
Error when trying to view Sms in debug toolbar

### ISSUE THREAD

**Issue by onahkenneth** [scaytrase/symfony-sms-interface#6]
Neither the property "service" nor one of the methods "service()", "getservice()"/"isservice()" or "__call()" exist and have public access in class "ScayTrase\SmsDeliveryBundle\DataCollector\MessageDeliveryDataCollector" in SmsDeliveryBundle:DataCollector:data_collector.html.twig at line 70

**Comment by scaytrase** [comment]
Thanks for reporting, looks like I've just forget to remove this after refactoring and haven't checked the profiler panel inside. I'll try to fix it soon
